### ISSUE TITLE
Add more books in the list enhancement New feature or request

### ISSUE THREAD

**Issue by pratik815** [pratik815/bookstore#2]
add a more books in our project

**Comment by pranits3229** [comment]
![c++](https://user-images.githubusercontent.com/114656173/194762357-64b43044-e928-47d5-b62c-2c31e3600087.jpg)
![java](https://user-images.githubusercontent.com/114656173/194762359-2625151b-c27a-42ef-b775-596573929034.jpg)
![python](https://user-images.githubusercontent.com/114656173/194762360-37bd694c-90cf-47e5-93e0-50083b5d1e83.jpg)
